# ASSIGNMENT CONFIG
tests:
    ok_format: false
    files: true
generate: true
export_cell: false

# Lab 1: Basic operations and Environmental Justice

The **objectives** of this lab are to:

1. practice basic operations in Pandas; 
2. build dataframes from scratch; 
3. import libraries and data.

In [1]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
import warnings

warnings.simplefilter(action='ignore')

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/danhammer/envirods/main/data/EJSCREEN_demo.csv")
df.head()

,ID,MINORPCT,LOWINCPCT,LESSHSPCT,PM25,PTSDF,P_LDPNT,P_LDPNT_D2,VULEOPCT
0,10010201001,0.163522,0.385220,0.208134,9.690899,0.586754,60.382488,38.762556,0.274371
1,10010201002,0.216006,0.163170,0.040678,9.690899,0.450601,41.403686,32.680975,0.189588
2,10010202001,0.676543,0.501247,0.135563,9.711240,0.653377,45.651211,74.665031,0.588895
3,10010202002,0.550082,0.393701,0.192000,9.711240,1.009395,66.398228,78.826782,0.471891
4,10010203001,0.340401,0.308217,0.125473,9.745683,1.177764,35.884283,44.665845,0.324309

In [3]:
df.describe()

,ID,MINORPCT,LOWINCPCT,LESSHSPCT,PM25,PTSDF,P_LDPNT,P_LDPNT_D2,VULEOPCT
count,2.203330e+05,220333.000000,220304.000000,220333.000000,216075.000000,220333.000000,217739.000000,217710.000000,220304.000000
mean,2.863577e+11,0.376564,0.338443,0.130912,8.471007,5.245966,57.284283,49.691055,0.357471
std,1.633201e+11,0.319043,0.215731,0.120827,1.490806,22.138310,27.750246,29.386438,0.231712
min,1.001020e+10,0.000000,0.000000,0.000000,4.004773,0.000000,11.066332,0.001475,0.000000
25%,1.312101e+11,0.098820,0.164911,0.042851,7.640858,0.178941,34.009956,23.180730,0.171342
50%,2.816395e+11,0.277911,0.305327,0.095923,8.514651,1.054927,60.362116,47.961951,0.294340
75%,4.200343e+11,0.623514,0.481818,0.184116,9.254252,3.229060,81.615782,75.760165,0.517744
max,7.215375e+11,1.000000,1.000000,1.000000,16.459907,442.427980,100.000000,100.000000,1.000000

# BEGIN QUESTIONS
name: q0_1

**Question 0.1:** Which of the columns in `df` are `float64` data types? Put these column names into a Python list and then assign it to `q0_1`.

In [4]:
# BEGIN SOLUTION

In [5]:
q0_1 = ["MINORPCT", "LOWINCPCT", "LESSHSPCT", "PM25", "PTSDF", "P_LDPNT", "P_LDPNT_D2", "VULEOPCT"] # SOLUTION
q0_1

['MINORPCT',
 'LOWINCPCT',
 'LESSHSPCT',
 'PM25',
 'PTSDF',
 'P_LDPNT',
 'P_LDPNT_D2',
 'VULEOPCT']

In [6]:
# END SOLUTION

In [7]:
# BEGIN TESTS

In [8]:
def test_q0_1(q0_1):
    assert len(q0_1) in [8, 9]
    assert "MINORPCT" in q0_1
    assert "LOWINCPCT" in q0_1
    assert "LESSHSPCT" in q0_1
    assert "PM25" in q0_1
    assert "PTSDF" in q0_1
    assert "P_LDPNT" in q0_1
    assert "P_LDPNT_D2" in q0_1
    assert "VULEOPCT" in q0_1

test_q0_1(q0_1)

In [9]:
# END TESTS

In [10]:
# END QUESTION

In [11]:
df.sort_values("LOWINCPCT",ascending=False).head()

,ID,MINORPCT,LOWINCPCT,LESSHSPCT,PM25,PTSDF,P_LDPNT,P_LDPNT_D2,VULEOPCT
220239,721455606002,0.970874,1.0,0.504225,NaN,0.324485,NaN,NaN,0.985437
97688,260730005003,0.141917,1.0,0.000000,6.895766,1.770340,64.980950,84.149977,0.570958
97685,260730004004,0.268182,1.0,0.179104,6.889775,3.263551,11.066332,62.800739,0.634091
130621,360290091101,0.494183,1.0,0.000000,7.998847,4.143470,11.066332,62.800739,0.747092
220289,721519508002,1.000000,1.0,0.311703,NaN,0.147915,NaN,NaN,1.000000